pipeline {
  agent {
    docker {
       image 'maven:3-alpine'
       args '-v /root/.m2:/root/.m2'
    }
  }
    environment {
      CREDENTIALS_ID = 'editors-1018029054589'
  }
  
  options {
     skipStagesAfterUnstable()
  }
  stages {
     stage ('Build') {
       steps {
          sh 'mvn -B -DskipTests clean package'
       }
   }
   stage ('Test') {
       steps {
           sh 'mvn test'
       }
       post {
          always {
             junit 'target/surefire-reports/*.xml'
          }
       }
   }
   stage ('Deliver') {
       steps { 
          sh './jenkins/scripts/deliver.sh'
       }
   }
   stage ('Push') {
      steps {
         sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERAME; echo
             password=\\$GIT_PASSWORD; } p"'
         sh 'git tag -m "" ${VERSION_NUMBER} '
         withCredentials {[
             usernamePAssword(credentialsId: 'github', usernameVariable: 'GIT_USERNAME',
             passwordVariable: 'GIT_PASSWORD')
             ]) {
                  sh 'git push origin ${VERSION_NUMBER}'
            }
      }
  }
 }
}
