pipeline {
  agent any {
    docker {
       image 'maven:3-alpine'
       args '-v /root/.m2:/root/.m2'
    }
    environment {
      CREDENTIALS_ID = 'editors-1018029054589'
  }
  }
  options {
     skipStagesAfterUnstable()
  }
  stages {
     stage ('Build') {
       steps {
          sh 'mvn -B -DskipTests clean package'
       }
   }
   stage ('Test') {
       steps {
           sh 'mvn test'
       }
       post {
          always {
             junit 'target/surefire-reports/*.xml'
          }
       }
   }
   stage ('Deliver') {
       steps { 
          sh './jenkins/scripts/deliver.sh'
       }
   }
   stage ('Download from GCS') {
       steps {
             step{
               step([$class: 'DownloadStep', credentialsId: env.CREDENTIALS_ID,
                      bucketUri: 'CappSample*.car', localDirectory: '/var/jenkins_home/workspace/'
                   ])
             }
      }
   }
 }
}
